const users = {
    a001: {
        id: 'a001',
        account: 'a001',
        email: 'David@gmail.com',
        password: 'abc123',
        name: 'David',
        age: 18,
        gender: 1,
        tel: '0900-001-001',
        city: 0,
        district: '100',
        address: '徐州路xxx號',
    },
    a002: {
        id: 'a002',
        account: 'a002',
        email: 'Mary@gmail.com',
        password: 'abc123',
        name: 'Mary',
        age: 18,
        gender: 0,
        tel: '0900-001-002',
        city: 1,
        district: '220',
        address: '中山路一段xxx號',
    },
    a003: {
        id: 'a003',
        account: 'a003',
        email: 'John@gmail.com',
        password: 'abc123',
        name: 'John',
        age: 18,
        gender: 1,
        tel: '0900-001-003',
        city: 2,
        district: '330',
        address: '正光路xxx號',
    },
    a004: {
        id: 'a004',
        account: 'a004',
        email: 'Lucy@gmail.com',
        password: 'abc123',
        name: 'Lucy',
        age: 18,
        gender: 0,
        tel: '0900-001-004',
        city: 3,
        district: '302',
        address: '光明六路xxx號',
    },
}

module.exports = users
